### ISSUE TITLE
MapNode Glitch

### ISSUE THREAD

**Issue by Lake25** [JamesVeug/InscyptionZergMod#2]
So, there is this node completely blocking my path and I found out its the zerg mod node cus I went through each mod I had on, anyways, it starts off by sending you into the thing, saying "a green slug approaches you" leshies eyes go all green and everything... and thats it. it just freezes, permanently, forcing you to reset save data if you have no other map options. Please fix this so I can keep playing inscryption without this worry.

**Comment by JamesVeug** [comment]
@Lake25 Next time you get this can you post all of the logs from the console?
Otherwise i can't trackdown what the issue is

Cheers
